return {
	"Abyssal Zenith",
	"Ancient Archives",
	"Ancient Isle",
	"Atlantean Storm",
	"Atlantis",
	"Brine Pool",
	"Calm Zone",
	"Challenger's Deep",
	"Cryogenic Canal",
	"Desolate Deep",
	"Forsaken Shores",
	"Frigid Cavern",
	"Glacial Grotto",
	"Grand Reef",
	"Keepers Altar",
	"Moosewood",
	"Mushgrove",
	"Ocean",
	"Overgrowth Caves",
	"Roslit",
	"Roslit Volcano",
	"Snowcap",
	"Sunstone",
	"Terrapin",
	"The Depths",
	"Veil of the Forsaken",
	"Vertigo",
	"Volcanic Vents"
}
