return {
	["Tentacle Surge"] = { Multiplier = 10, Appraisable = false },
	["Prismize"] = { Multiplier = 8, Appraisable = false },
	["Aurora"] = { Multiplier = 6.5, Appraisable = false },
	["Wrath"] = { Multiplier = 6.5, Appraisable = false },
	["Aureolin"] = { Multiplier = 6, Appraisable = false },
	["Ashen Fortune"] = { Multiplier = 5, Appraisable = false },
	["Aurulent"] = { Multiplier = 5, Appraisable = false },
	["Heavenly"] = { Multiplier = 5, Appraisable = false },
	["Subspace"] = { Multiplier = 5, Appraisable = false },
	["Mythical"] = { Multiplier = 4.5, Appraisable = true },
	["Aureate"] = { Multiplier = 4, Appraisable = false },
	["Greedy"] = { Multiplier = 4, Appraisable = true },
	["Nuclear"] = { Multiplier = 4, Appraisable = false },
	["Revitalized"] = { Multiplier = 4, Appraisable = false },
	["Sunken"] = { Multiplier = 4, Appraisable = false },
	["Abyssal"] = { Multiplier = 6.5, Appraisable = true },
	["Electric Shock"] = { Multiplier = 3.5, Appraisable = false },
	["King's Blessing"] = { Multiplier = 3.5, Appraisable = false },
	["Atlantean"] = { Multiplier = 3, Appraisable = false },
	["Aurelian"] = { Multiplier = 3, Appraisable = false },
	["Blighted"] = { Multiplier = 3, Appraisable = false },
	["Seasonal (Spring)"] = { Multiplier = 3, Appraisable = false },
	["Anomalus"] = { Multiplier = 2.5, Appraisable = false },
	["Fossilized"] = { Multiplier = 2.5, Appraisable = true },
	["Lunar"] = { Multiplier = 2.5, Appraisable = true },
	["Seasonal (Winter)"] = { Multiplier = 2.5, Appraisable = false },
	["Solarblaze"] = { Multiplier = 2.5, Appraisable = false },
	["Sleet"] = { Multiplier = 2.5, Appraisable = false },
	["Aurous"] = { Multiplier = 2, Appraisable = false },
	["Celestial"] = { Multiplier = 2, Appraisable = false },
	["Midas"] = { Multiplier = 2, Appraisable = true },
	["Purified"] = { Multiplier = 2, Appraisable = false },
	["Crystalized"] = { Multiplier = 1.75, Appraisable = false },
	["Glossy"] = { Multiplier = 1.6, Appraisable = true },
	["Silver"] = { Multiplier = 1.6, Appraisable = true },
	["Mosaic"] = { Multiplier = 1.5, Appraisable = true },
	["Hexed"] = { Multiplier = 1.5, Appraisable = true },
	["Electric"] = { Multiplier = 1.45, Appraisable = true },
	["Darkned"] = { Multiplier = 1.3, Appraisable = true },
	["Frozen"] = { Multiplier = 1.3, Appraisable = true },
	["Negative"] = { Multiplier = 1.3, Appraisable = true },
	["Scorched"] = { Multiplier = 1.3, Appraisable = true },
	["Seasonal (Summer/Autumn)"] = { Multiplier = 1.3, Appraisable = false },
	["Translucent"] = { Multiplier = 1.3, Appraisable = true },
	["Albino"] = { Multiplier = 1.1, Appraisable = true },
	["Studded"] = { Multiplier = 1.1, Appraisable = false },
	["Lightning"] = { Multiplier = 1, Appraisable = false },
	["Amber"] = { Multiplier = 0.5, Appraisable = true },
	["Charred"] = { Multiplier = 0.5, Appraisable = false }
}
