name: Unzip Main Project

on:
  push:
    branches:
      - main # Hanya berjalan jika ada push ke branch 'main'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Unzip the project file
        # Ganti 'proyek.zip' dengan nama file zip Anda
        run: unzip proyek.zip

      - name: Commit and push changes
        run: |
          # Hapus file zip asli agar tidak ada duplikasi
          rm proyek.zip

          # Konfigurasi user Git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Tambahkan file yang sudah diekstrak dan commit
          git add .
          git commit -m "CI: auto unzip project files" || echo "No changes to commit"

          # Push perubahan ke repositori
          git push
          
